"""Configuration loading with sensible defaults.

Reads ``config.json`` (kept out of git — copy ``config.example.json``). Missing keys
fall back to the defaults below so an older config keeps working after an update.
"""

import json

_DEFAULTS = {
    "wifi_ssid": "",
    "wifi_pass": "",
    "static_ip": "",          # empty => use DHCP
    "subnet": "255.255.255.0",
    "gateway": "",
    "dns": "8.8.8.8",
    "http_port": 80,
    "secret": "",             # base64 32-byte HMAC key, generated by the app
    "duckdns_domain": "",     # empty => DDNS disabled
    "duckdns_token": "",
    "ntp_host": "pool.ntp.org",
}


def load(path="config.json"):
    with open(path) as f:
        user = json.load(f)
    cfg = dict(_DEFAULTS)
    cfg.update(user)
    return cfg
